server:
  port: 8092

spring:
  application:
    name: ldms-fuel-expenses
  datasource:
    url: jdbc:mysql://localhost:3306/ldms_fuel_expenses?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: ${DB_USERNAME:${MYSQL_USER:developer}}
    password: ${DB_PASSWORD:${MYSQL_DEVELOPER_PASSWORD:Password098()!}}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true

management:
  server:
    port: 9092

  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
clients:
  base-url:
    billing-payments: http://ldms-billing-payments
    trip-tracking: http://ldms-trip-tracking
