server:
  port: 8094

spring:
  application:
    name: notifications
  datasource:
    url: jdbc:mysql://localhost:3306/ldms_notifications?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: ${DB_USERNAME:${MYSQL_USER:developer}}
    password: ${DB_PASSWORD:${MYSQL_DEVELOPER_PASSWORD:Password098()!}}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true

management:
  server:
    port: 9094

  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
ldms:
  notifications:
    rabbitmq:
      exchange: ldms.notifications.exchange
      queue: ldms.notifications.queue
      routing-key: notification.send
