server:
  port: 8089

spring:
  application:
    name: ldms-fleet-management
  datasource:
    url: jdbc:mysql://localhost:3306/ldms_fleet_management?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: ${DB_USERNAME:${MYSQL_USER:developer}}
    password: ${DB_PASSWORD:${MYSQL_DEVELOPER_PASSWORD:Password098()!}}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true

management:
  server:
    port: 9089

  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
clients:
  base-url:
    documents-management: http://ldms-documents-management
    user-management: http://ldms-user-management

ldms:
  fleet:
    compliance-warning-days: 30
